--- ## Now we are working the the Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  annotations: 
    description: "this is my replica set annotations !!!"
  labels:
    env: development
    class: pods
    love: devops
    object: deployment
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [development, deploy, develop]}
      - {key: myname, operator: NotIn, values: [prod, production]}
  template:
    metadata:
      name: testpod
      annotations:
        description: "this is my replica set testpod's annotations !!"
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: shubhamsonirg/myimage7
          env:
            - name: MYNAME
              value: DEPLOYMENT
          ports:
            - containerPort: 80
