--- ## Now we are working with the config map
kind: Pod
apiVersion: v1
metadata:
  name: myconfigmap
  annotations:
    description: "Now we are working with the config map !!"
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: centos
      args:
        - /bin/bash
        - -c
        - while true; do echo "hello shubham"; sleep 5; done
      env:
        - name: MYENV
          valueFrom:
            configMapKeyRef:
              name: mymap
              key: sample.conf
