kind: Pod
apiVersion: v1
metadata:
  name: mysecret
  annotations:
    description: "Now we are working with the config map !!"
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: centos
      args:
        - /bin/bash
        - -c
        - while true; do echo "hello shubham"; sleep 5; done
      env:
        - name: MYENV
          valueFrom:  
            secretKeyRef:
              name: mysecret
              key: username.txt

        - name: MYENV-PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password.txt
