kind: Pod
apiVersion: v1
metadata:
  name: myconfigmap
  annotations:
    description: "Now we are working with the config map !!"
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: centos
      args:
        - /bin/bash
        - -c
        - while true; do echo "hello shubham"; sleep 5; done
      volumeMounts:
        - name: mysec
          mountPath: "/tmp/mysec"
  volumes:
    - name: mysec
      secret:
        secretName: mysecret
