apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo
  namespace: dev
spec:
  containers:
  - name: constraints-mem-demo-ctr
    image: nginx
    resources:
      limits:
         cpu: 1 
      requests:
         cpu: 50m
