--- # Now with this manifest we are requesting the cluster provide the storage volume to our pods
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
  annotations:
    description: "Now with this manifest we are requesting the cluster provide the storage volume to our pods"
  labels:
    env: development
    class: pods
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
  template:
    metadata: 
      name: testpod
      annotations: 
        description: "This is testpod annotation !!"
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: shubhamsonirg/kubernetesproject
          env:
            - name: MYNAME
              value: PVC
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - cat 
                - /var/www/html/index.html
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
