--- ## Now we are working with the Replication controller
kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica
  annotations: 
    description: "Now we are working with the Replication controller !!!"
  labels:
    env: development
    class: pods
spec:
  replicas: 2
  selector:
      env: development
  template:
    metadata:
      name: testpod
      annotations:
        description: "this is testpod description !!"
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: shubhamsonirg/myimage7
          env:
            - name: MYNAME
              value: REPLICATIONCONTROLLER
          ports:
            - containerPort: 80
    
  
